# Black formatting
[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | _build
    | buck-out
    | build
    | dist
    | \.venv_*/
    | ./content/.*\.py
  )/
'''

[tool.pylint]
    [tool.pylint.'MESSAGES CONTROL']
    disable = [
        "access-member-before-definition",
        "attribute-defined-outside-init",
        "duplicate-code",
        "logging-fstring-interpolation",
        "no-member",
    ]
