train_loader:
  batch_size: 64
  shuffle: True
  num_workers: 4
  pin_memory: True
  drop_last: True
    
valid_loader:
  batch_size: 64
  shuffle: False
  num_workers: 4
  pin_memory: True
  drop_last: False