defaults:
  - _self_

models:
  _target_: torchvision.models.vgg16

classes:
  [
              "aeroplane",
              "bicycle",
              "bird",
              "boat",
              "bottle",
              "bus",
              "car",
              "cat",
              "chair",
              "cow",
              "diningtable",
              "dog",
              "horse",
              "motorbike",
              "person",
              "pottedplant",
              "sheep",
              "sofa",
              "train",
              "tvmonitor",
          ]


hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${now:%Y-%m-%d_%H-%M-%S}_${hydra.job.num}_${datamodule.fold_n}